### ISSUE TITLE
Deep in into next feature of Git.

### ISSUE THREAD

**Issue by chez14** [eldon97/contoh#1]
Hi Eldon,

Let's add a little text there, to the [README.md](https://github.com/eldon97/contoh/blob/master/README.md). It won't be a hard thing to do, just add a little text there like `Loremp Ipsum` or something else there. Don't forget to mention the commit to this issue.

Just make sure that you changed the README.md, and push it here.

**A little tip**: To mention this issue, you can use the hashtag `#` symbol, and a number to mention your commits here. For example, this is the commit message:
```
update for issue #1
-- added more text to the README.md
```

The numbers are the issue's number. It located on the next of the title of the issue.

**Bonus point** if you do it by creating a branch first, then merge it to the `master` branch, it's optional, but we'll do it someday, near... hoho.

**Comment by chez14** [comment]
Naise!

You've done great so far, let's continue... let's train `.gitignore`!

`.gitignore` is a file specified by Git to ignore changes to some files. For example, Net Beans sometimes generate cache files that are required for the software to run properly. But this file constantly changes and pollute the commits.

Next task:
- Make a `.gitignore` file, let's just ignore your `contoh_file.txt`. [Here's your references](https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#Ignoring-Files), scroll down to **Ignoring Files** section.
- Commit the `.gitignore` file.
- Make changes to `contoh_file.txt` we'll see the Source Tree won't notice it changes.

  You'll not be able to stage your `contoh_file.txt` file since Git didn't notice it's changed. It's ok, it's an expected behavior one.
- Push it to Github, and close this issue by adding `fix #1` to the commit message body.

**Comment by chez14** [comment]
Ayy don't close this issue, yet xD we haven't done this chapter yet...

Press `Reopen` button, this will be reopened.

**Comment by levint55** [comment]
woi bangsat kalian

**Comment by eldon97** [comment]
@levint55 merusak issue saja kau

**Comment by levint55** [comment]
udh cape ,mending tidor

**Comment by chez14** [comment]
Ok, I haven't tried that either one of it. I'll give an update to you when I got a chance to try it.

**Next, let's do a rollback!**

Git is a special tool that can be used to roll back any mistake we made to a certain commit. Let's try it with rolling it back to the first commit of yours!

You can do it using **Source Tree**.
- Go to Log/History tab (check it on the bottom part of the project.)
- Scroll down to your first commit
- Right Click, then find the *Reset this branch to this commit* menu.

Then you'll make a new commit, automatically, then don't forget to push the changes.

@levint55 Welcome to the @eldon97's course. Wanna get this course too?

**Comment by chez14** [comment]
Let's move into the new issue, #2

**Comment by chez14** [comment]
Oh one more, if you have some questions about this chapter, you can always comment on this, or even reopen it.

sorry for late response, i'm being unstable lately, i have to take more rest hahahah lol.

**Comment by eldon97** [comment]
thank you so much for this chapter @chez14 muach muach :)
